### ISSUE TITLE
Barcodes?

### ISSUE THREAD

**Issue by minig0d** [hunternet93/dymo-web-service-clone#2]
Any chance barcodes can be generated with this?

Already tried a barcode font in the SVG template except the barcode fonts need checkdigit encoding and all...  (well above my python knowledge)

**Comment by hunternet93** [comment]
Unfortunately the program doesn't have that feature, and I don't plan to add it. I'd be happy to accept a pull request for it if you or someone else codes the feature, though.

**Comment by qwertychouskie** [comment]
I'd love to see this feature too, trying to move away from Windows on one of the work systems.
